### ISSUE TITLE
Coworking page broken

### ISSUE THREAD

**Issue by pixelyunicorn** [phillystartupleaders/psl#11]
As a heads up, the Coworking page is broken.
![image](https://cloud.githubusercontent.com/assets/607807/9964726/e7d58cbc-5dff-11e5-9d9d-1d3d068ad696.png)

**Comment by ChrisSki** [comment]
@LabLayers is this still broken? It seems to be working fine on my end.

**Comment by pixelyunicorn** [comment]
It's working now.
